// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAfJgFHZY-C5l7xEGznFSQ88Bs7-PGHaw',
    appId: '1:952546028396:web:26e8dae85b995e7d8da149',
    messagingSenderId: '952546028396',
    projectId: 'micforall-42175',
    authDomain: 'micforall-42175.firebaseapp.com',
    storageBucket: 'micforall-42175.appspot.com',
    measurementId: 'G-F25EFHYLYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb63hAWjDjuDS5xvD6T4EdQf9CnGaztpE',
    appId: '1:952546028396:android:8273ff51b0ffd2008da149',
    messagingSenderId: '952546028396',
    projectId: 'micforall-42175',
    storageBucket: 'micforall-42175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx_kYWAYaeUFIBRRuStNi6BaU6GaxKj7k',
    appId: '1:952546028396:ios:162ddd7d2bb5acb08da149',
    messagingSenderId: '952546028396',
    projectId: 'micforall-42175',
    storageBucket: 'micforall-42175.appspot.com',
    iosBundleId: 'com.example.arboFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx_kYWAYaeUFIBRRuStNi6BaU6GaxKj7k',
    appId: '1:952546028396:ios:162ddd7d2bb5acb08da149',
    messagingSenderId: '952546028396',
    projectId: 'micforall-42175',
    storageBucket: 'micforall-42175.appspot.com',
    iosBundleId: 'com.example.arboFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAfJgFHZY-C5l7xEGznFSQ88Bs7-PGHaw',
    appId: '1:952546028396:web:bb24d5f3f53e80ab8da149',
    messagingSenderId: '952546028396',
    projectId: 'micforall-42175',
    authDomain: 'micforall-42175.firebaseapp.com',
    storageBucket: 'micforall-42175.appspot.com',
    measurementId: 'G-PC6XM3L8QD',
  );
}
